-- QuickBite schema for PostgreSQL
--
-- Identifiers are double-quoted to keep the exact MixedCase names the app
-- (and the JSON returned by its API routes) relies on.
--
-- Apply with:  psql "$DATABASE_URL" -f QuickBite_schema.sql
-- WARNING: drops and recreates every table.

DROP TABLE IF EXISTS "Order_Contains", "Rating", "Customer_Order", "Customer_Address",
  "Coupon", "Cuisine", "Menu", "Payment", "Delivery_Address", "Customer", "Driver",
  "Restaurant", "Users" CASCADE;

CREATE TABLE "Users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(100) NOT NULL UNIQUE,
  "password" varchar(255) NOT NULL,
  "role" varchar(20) NOT NULL CHECK ("role" IN ('customer', 'restaurant', 'driver'))
);

CREATE TABLE "Customer" (
  "Customer_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Email" varchar(100),
  "Phone_Num" varchar(20),
  "First_Name" varchar(50),
  "Middle_Name" varchar(50),
  "Last_Name" varchar(50),
  "userId" integer REFERENCES "Users" ("id")
);
CREATE INDEX "fk_customer_user" ON "Customer" ("userId");

CREATE TABLE "Driver" (
  "Driver_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(100),
  "Vehicle_Name" varchar(100),
  "Vehicle_Number" varchar(50),
  "Email" varchar(100),
  "userId" integer REFERENCES "Users" ("id")
);
CREATE INDEX "fk_driver_user" ON "Driver" ("userId");

CREATE TABLE "Restaurant" (
  "Restaurant_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Restaurant_Name" varchar(100),
  "Address_First_line" varchar(255),
  "Address_Second_line" varchar(255),
  "City" varchar(100),
  "Pincode" varchar(20),
  "userId" integer REFERENCES "Users" ("id"),
  "Email" varchar(100),
  "Phone" varchar(20)
);
CREATE INDEX "fk_restaurant_user" ON "Restaurant" ("userId");

CREATE TABLE "Delivery_Address" (
  "Address_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Address_First_Line" varchar(255),
  "Address_Second_Line" varchar(255),
  "City" varchar(100),
  "Pincode" varchar(20)
);

CREATE TABLE "Customer_Address" (
  "Customer_ID" integer NOT NULL,
  "Address_ID" integer NOT NULL REFERENCES "Delivery_Address" ("Address_ID"),
  PRIMARY KEY ("Customer_ID", "Address_ID")
);
CREATE INDEX "customer_address_address_idx" ON "Customer_Address" ("Address_ID");

CREATE TABLE "Cuisine" (
  "Restaurant_ID" integer PRIMARY KEY REFERENCES "Restaurant" ("Restaurant_ID"),
  "Cusine" varchar(100) NOT NULL
);

CREATE TABLE "Menu" (
  "Menu_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Item_Name" varchar(100),
  "Item_Description" varchar(255),
  "Price" numeric(10,2),
  "Restaurant_ID" integer REFERENCES "Restaurant" ("Restaurant_ID")
);
CREATE INDEX "fk_menu_restaurant" ON "Menu" ("Restaurant_ID");

CREATE TABLE "Coupon" (
  "Coupon_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Discount" numeric(5,2),
  "Expiry" date,
  "Restaurant_ID" integer REFERENCES "Restaurant" ("Restaurant_ID")
);
CREATE INDEX "coupon_restaurant_idx" ON "Coupon" ("Restaurant_ID");

CREATE TABLE "Payment" (
  "Payment_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Amount" numeric(10,2),
  "Payment_Method" varchar(50),
  "Date" date,
  "Status" varchar(50)
);

CREATE TABLE "Customer_Order" (
  "Order_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Status" varchar(50),
  "Customer_ID" integer REFERENCES "Customer" ("Customer_ID"),
  "Address_ID" integer REFERENCES "Delivery_Address" ("Address_ID"),
  "Restaurant_ID" integer REFERENCES "Restaurant" ("Restaurant_ID"),
  "Payment_ID" integer REFERENCES "Payment" ("Payment_ID"),
  "Driver_ID" integer REFERENCES "Driver" ("Driver_ID"),
  "Created_At" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "Coupon_ID" integer REFERENCES "Coupon" ("Coupon_ID")
);
CREATE INDEX "fk_co_restaurant" ON "Customer_Order" ("Restaurant_ID");
CREATE INDEX "fk_co_driver" ON "Customer_Order" ("Driver_ID");
CREATE INDEX "fk_co_customer" ON "Customer_Order" ("Customer_ID");
CREATE INDEX "fk_co_address" ON "Customer_Order" ("Address_ID");
CREATE INDEX "fk_co_payment" ON "Customer_Order" ("Payment_ID");
CREATE INDEX "fk_co_coupon" ON "Customer_Order" ("Coupon_ID");

CREATE TABLE "Order_Contains" (
  "Order_ID" integer NOT NULL REFERENCES "Customer_Order" ("Order_ID"),
  "Menu_ID" integer NOT NULL,
  "Quantity" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("Order_ID", "Menu_ID")
);
CREATE INDEX "order_contains_menu_idx" ON "Order_Contains" ("Menu_ID");

CREATE TABLE "Rating" (
  "Review_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Rating" integer,
  "Restaurant_ID" integer REFERENCES "Restaurant" ("Restaurant_ID"),
  "Order_ID" integer NOT NULL,
  "Customer_ID" integer NOT NULL
);
CREATE INDEX "rating_restaurant_idx" ON "Rating" ("Restaurant_ID");

-- ---------------------------------------------------------------------------
-- Functions
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_avg_rating(resto_id integer)
RETURNS numeric(3,2) LANGUAGE sql STABLE AS $$
  SELECT COALESCE(AVG("Rating"), 0)::numeric(3,2)
  FROM "Rating"
  WHERE "Restaurant_ID" = resto_id
$$;

CREATE OR REPLACE FUNCTION fn_driver_earning(amount numeric(10,2))
RETURNS numeric(10,2) LANGUAGE sql IMMUTABLE AS $$
  SELECT (amount * 0.05 + 30)::numeric(10,2) -- 30 is base delivery fee
$$;

CREATE OR REPLACE FUNCTION fn_restaurant_earning(amount numeric(10,2))
RETURNS numeric(10,2) LANGUAGE sql IMMUTABLE AS $$
  SELECT (amount * 0.75)::numeric(10,2)
$$;

CREATE OR REPLACE FUNCTION fn_platform_fee(amount numeric(10,2))
RETURNS numeric(10,2) LANGUAGE sql IMMUTABLE AS $$
  SELECT amount - fn_restaurant_earning(amount) - fn_driver_earning(amount)
$$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

-- Mark the payment as Paid once an order is delivered (covers COD orders).
CREATE OR REPLACE FUNCTION trg_order_delivered_update_payment()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."Status" = 'Delivered' AND OLD."Status" IS DISTINCT FROM 'Delivered'
     AND NEW."Payment_ID" IS NOT NULL THEN
    UPDATE "Payment" SET "Status" = 'Paid' WHERE "Payment_ID" = NEW."Payment_ID";
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_order_delivered_update_payment
AFTER UPDATE ON "Customer_Order"
FOR EACH ROW EXECUTE FUNCTION trg_order_delivered_update_payment();
